
#pragma once


enum { // VERY CAREFUL, FOLLOWING VALUES ARE SERIALIZED!!
        SIM_IDSTART_3DOBJECT            =0,
        SIM_IDSTART_COLLECTION_OLD      =100000,
        SIM_IDEND_3DOBJECT              =1999999,
        SIM_IDSTART_COLLECTION          =2000000,
        SIM_IDEND_COLLECTION            =SIM_IDSTART_COLLECTION+10000,
        SIM_IDSTART_COLLISION           =SIM_IDEND_COLLECTION+1,
        SIM_IDEND_COLLISION             =SIM_IDSTART_COLLISION+10000,
        SIM_IDSTART_DISTANCE            =SIM_IDEND_COLLISION+1,
        SIM_IDEND_DISTANCE              =SIM_IDSTART_DISTANCE+10000,
        SIM_IDSTART_IKGROUP             =SIM_IDEND_DISTANCE+1,
        SIM_IDEND_IKGROUP               =SIM_IDSTART_IKGROUP+10000,
        SIM_IDSTART_GCSOBJECT           =SIM_IDEND_IKGROUP+1,
        SIM_IDEND_GCSOBJECT             =SIM_IDSTART_GCSOBJECT+10000,
        SIM_IDSTART_LUASCRIPT           =SIM_IDEND_GCSOBJECT+1,
        SIM_IDEND_LUASCRIPT             =SIM_IDSTART_LUASCRIPT+10000,
        SIM_IDSTART_2DELEMENT           =SIM_IDEND_LUASCRIPT+1,
        SIM_IDEND_2DELEMENT             =SIM_IDSTART_2DELEMENT+10000,
        SIM_IDSTART_PATHPLANNINGTASK    =SIM_IDEND_2DELEMENT+1,
        SIM_IDEND_PATHPLANNINGTASK      =SIM_IDSTART_PATHPLANNINGTASK+10000,
        SIM_IDSTART_GEOMETRIC_OLD       =SIM_IDEND_PATHPLANNINGTASK+1,
        SIM_IDEND_GEOMETRIC_OLD         =SIM_IDSTART_GEOMETRIC_OLD+100000,
        SIM_IDSTART_TEXTURE             =SIM_IDEND_GEOMETRIC_OLD+1,
        SIM_IDEND_TEXTURE               =SIM_IDSTART_TEXTURE+100000,
        SIM_IDSTART_MOTIONPLANNINGTASK  =SIM_IDEND_TEXTURE+1,
        SIM_IDEND_MOTIONPLANNINGTASK    =SIM_IDSTART_MOTIONPLANNINGTASK+10000,
};
